### ISSUE TITLE
RE-STYLING !! 

### ISSUE THREAD

**Issue by Artowod** [Shadic78/react-native-basic-pagination#4]
Dear developer,
your product is what many people need! - simple , only useful functions  and minimum visual things. no any dots or other useless icons! Bravo !
BUT - dark squares as a background... looks like you developed it for yourself Only.

Kindly ask you to ...Or implement possibility to change Styles ...or delete that squares.. leaving only text.

i assume would be correct ( obviously it`s how usually do all other developers) to add additional props to change your default styling .  ( it`s soo easy - possibility to change background, color , textFamily , text size etc) ...  and your Product will shine as much as possible i`m really sure !!!

Greetings !

**Comment by Shadic78** [comment]
Hi @Artowod.
Your right, I developed this package for myself and published it on npm as my first package with the hope that at least one developer other than me may find it useful but I didn't have much hope about it so I left this thing unfinished.

Your issue made my day so now in #5  I implemented support for custom styles. You can take a look if you wish!
